repos:
- maps
rotation: rotation.txt
deleteMatches: true
displayMapLoadErrors: false
custom-motd: true
worldEditPermissions: true
server-message: Scrimmage Server
cycle: -1
matchTimeMillis: true
observers-ready: true
html:
  upload: true
  transcriptMilliseconds: true
permissions:
  Default:
    permissions:
    - cardinal.chat.global
    - cardinal.chat.team
  Moderator:
    permissions:
    - cardinal.say
    - cardinal.broadcast
    - cardinal.mod
    - tnt.defuse
    - cardinal.cancel
    - cardinal.chat.admin
    - cardinal.match.setnext
    - cardinal.match.end
    - cardinal.match.start
    - cardinal.match.cycle
    - cardinal.team.force
    - cardinal.team.alias
    - cardinal.teleport
    - whitelist.reload
    - whitelist.toggle
    - whitelist.on
    - whitelist.off
    - whitelist.status
    - whitelist.add
    - whitelist.remove
    - whitelist.list
    - whitelist.team
    - whitelist.kick
    - cardinal.punish.warn
    - cardinal.punish.kick
    - cardinal.punish.ban
    - cardinal.punish.mute
    - minecraft.command.pardon
    players:
settings:
- Blood
- DeathMessages
- HighlightDeathMessages
- JoinMessages
- Observers
- Picker
- PrivateMessages
- Scoreboard
- Sounds
- Stats
setting:
  Blood:
    values:
    - 'on'
    - off[default]
    description: See blood when players get hurt
  DeathMessages:
    aliases:
    - dms
    values:
    - own
    - all[default]
    description: Death messages displayed to you
  HighlightDeathMessages:
    aliases:
    - hdms
    values:
    - underline
    - italics
    - white
    - none
    - bold[default]
    description: Highlight death messages that you are involved in
  JoinMessages:
    aliases:
    - jms
    values:
    - none
    - all[default]
    description: Join messages displayed to you
  Observers:
    aliases:
    - obs
    values:
    - none
    - all[default]
    description: See other observers while spectating
  Picker:
    values:
    - 'off'
    - on[default]
    description: Open a helpful GUI for picking classes and teams
  PrivateMessages:
    aliases:
    - pms
    values:
    - none
    - all[default]
    description: Who can send you private messages
  Scoreboard:
    values:
    - 'off'
    - on[default]
    description: See the scoreboard with game information
  Sounds:
    values:
    - 'off'
    - on[default]
    description: Hear sounds to alert you of the last three seconds of a countdown
  Stats:
    values:
    - 'off'
    - on[default]
    description: See your statistics at the end of the game
